name: Publish to TestPyPI

on:
  workflow_dispatch:

permissions:
  attestations: write
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/pyquestblue
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.13"
      - run: python -m pip install build
      - run: python -m build
      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-path: "dist/*"
      - uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
